name: Merge if htaccess is ok 

on:
  push:
    branches:
      - integration

jobs:
  merge_on_file_existence:
    runs-on: ubuntu-latest
    permissions:                
      contents: write          
      pull-requests: write  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "anthonybs.pro@gmail.com"
        git config --global user.name "AnThONy77"
        git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/AnTh0Ny77/Planning.git

    - name: Check if htaccessDev exists
      run: |
        ls -la
        if [ -f ".htaccessDev" ]; then
          echo "htaccess is ok. Merging with master branch."
        else
          echo "htaccessDev does not exist please check htaccess configuration. No merge needed."
        fi

    - name: List branches
      run: git branch -a

    - name: Push changes to master
      if: success() && steps.check_if_file_exists.outputs.return_code == 0
      run: |
        git push origin integration
