name: Merge if htaccess is ok 

on:
  push:
    branches:
      - integration

jobs:
  merge_on_file_existence:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if htaccessDev exists
      run: |
        ls -la
        if [ -f ".htaccessDev" ]; then
          echo "htaccess is ok. Merging with master branch."
        else
          echo "htaccessDev does not exist please check htaccess configuration. No merge needed."
        fi

    - name: Push changes to master
      if: success() && steps.check_if_file_exists.outputs.return_code == 0
      run: |
        git push master
